
ALTER TABLE EMPLEADO
ADD CONSTRAINT FK_TIPO_EMPLEADO FOREIGN KEY(TIPO_EMPLEID)
	REFERENCES TIPO_EMPLEADO(TIPO_EMPLEID)
	ON DELETE RESTRICT ON UPDATE RESTRICT;
	
ALTER TABLE CONTRATO_MEMBRESIA
ADD	CONSTRAINT FK_EMPLEADO FOREIGN KEY (ID_EMPLE)
	REFERENCES EMPLEADO (ID_EMPLE)
	ON DELETE RESTRICT ON UPDATE RESTRICT;
	
ALTER TABLE CONTRATO_MEMBRESIA
ADD	CONSTRAINT FK_TIPO_MEMBRESIA FOREIGN KEY (ID_TIPOMEMBRE)
	REFERENCES TIPO_MEMBRESIA (ID_TIPOMEMBRE)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CONTRATO_MEMBRESIA
ADD	CONSTRAINT FK_CLIENTE FOREIGN KEY (ID_CLIENT)
	REFERENCES CLIENTE (ID_CLIENT)
	ON DELETE RESTRICT ON UPDATE RESTRICT;
	
ALTER TABLE FACTURACION_MENSUAL
ADD	CONSTRAINT FK_MEMBRESIA FOREIGN KEY (ID_MEMBRE)
	REFERENCES CONTRATO_MEMBRESIA (ID_MEMBRE)
	ON DELETE RESTRICT ON UPDATE RESTRICT;
	
ALTER TABLE CLIENTE 
ADD	CONSTRAINT FK_RUTINA FOREIGN KEY (ID_RUTIN)
	REFERENCES RUTINA (ID_RUTIN)
	ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE SEGUIMIENTO_RUTINA
ADD	CONSTRAINT FK_EMPLEADO FOREIGN KEY (ID_EMPLE)
	REFERENCES EMPLEADO (ID_EMPLE)
	ON DELETE RESTRICT ON UPDATE RESTRICT;
	
ALTER TABLE SEGUIMIENTO_RUTINA
ADD CONSTRAINT FK_RUTINA  FOREIGN KEY (ID_RUTIN)
	REFERENCES RUTINA (ID_RUTIN)
	ON DELETE RESTRICT ON UPDATE RESTRICT;
	
