CREATE TABLE CLIENTE (
	ID_CLIENT INT,
	CI_CLIENT VARCHAR(10),
	NOMBRE_CLIENTE VARCHAR(60),
	TELF_CLIENTE VARCHAR(10),
	FECHA_REGISTRO DATE,
	ID_ENTRENADOR INT,
	CONSTRAINT PK_CLIENTE PRIMARY KEY(ID_CLIENT)
);


CREATE TABLE EMPLEADO (
	ID_EMPLE INT,
	TIPO_EMPLEID INT,
	CI_EMPLEADO VARCHAR(10),
	NAME_EMPLEADO VARCHAR(60),
	DIRECCION VARCHAR(50),
	FECHA_NACIMIENTO DATE,
	FECHA_INGRESO DATE,
	CONSTRAINT PK_EMPLEADO PRIMARY KEY(ID_EMPLE)
);

CREATE TABLE TIPO_EMPLEADO (
	TIPO_EMPLEID INT,
	TIPO_EMPLEADO Text,
	CONSTRAINT PK_TIPO_EMPLEADO PRIMARY KEY(TIPO_EMPLEID)
);

CREATE TABLE CONTRATO_MEMBRESIA (
	ID_MEMBRE INT,
	ID_EMPLE INT,
	ID_CLIENT INT,
	ID_TIPOMEMBRE INT,
	VALOR_MEMBRESIA REAL,
	FECHA_CMEMBRESIA DATE,
	FECHA_VENCIMIENTO DATE,
	CONSTRAINT PK_CONTRATO_MEMBRESIA PRIMARY KEY(ID_MEMBRE)
);

CREATE TABLE TIPO_MEMBRESIA (
	ID_TIPOMEMBRE INT,
	TIPO_MEMBRESIA TEXT,
	CONSTRAINT PK_TIPO_MEMBRESIA PRIMARY KEY(ID_TIPOMEMBRE)	
);


CREATE TABLE FACTURACION_MENSUAL (
	ID_FACTU INT,
	ID_MEMBRE INT,
	VALOR_FACTURA REAL,
	FECHA_FACTURA DATE,
	CONSTRAINT PK_FACTURACION_MENSUAL PRIMARY KEY(ID_FACTU)
);

CREATE TABLE RUTINA (
	ID_RUTIN INT,
	ID_CLIENT INT,
	RUTINA_DESCRIP VARCHAR(60),
	CONSTRAINT PK_RUTINA PRIMARY KEY(ID_RUTIN)
);

CREATE TABLE SEGUIMIENTO_RUTINA (
	ID_SEGUI INT,
	ID_EMPLE INT,
	ID_RUTIN INT,
	DIAS_SEMANA VARCHAR(60),
	HORA_INICIAL TIME,
	HORA_fINAL TIME,
	ASISTENCIA BOOLEAN,
	CONSTRAINT PK_SEGUIMIENTO_RUTINA PRIMARY KEY(ID_SEGUI)
);
