
DO $$
DECLARE
	DATOS RECORD;
	DATOS2 RECORD;
	DATOS3 RECORD;
	DAT_EMPLEADO CURSOR FOR SELECT * FROM "empleado" ORDER BY "id_emple" ASC ;
	DAT_EMPLEADO2 CURSOR FOR SELECT ID_EMPLE FROM "contrato_membresia" GROUP BY "id_emple";
	DAT_EMPLEADO3 CURSOR FOR SELECT COUNT("id_emple") FROM Contrato_membresia GROUP BY "id_emple";
BEGIN
Open DAT_EMPLEADO;
FETCH DAT_EMPLEADO INTO DATOS;
while(FOUND) LOOP
RAISE NOTICE 'CODIGO: %, FECHA_INGRESO: %, ROL: %',DATOS.ID_EMPLE, DATOS.FECHA_INGRESO,DATOS.TIPO_EMPLEID;
FETCH DAT_EMPLEADO INTO DATOS;
end loop;

OPEN DAT_EMPLEADO2;
OPEN DAT_EMPLEADO3;
FETCH DAT_EMPLEADO2 INTO DATOS2;
FETCH DAT_EMPLEADO3 INTO DATOS3;
WHILE(FOUND) LOOP
RAISE NOTICE 'EMPLEADO: %, CANTIDAD_CLIENTES: %',DATOS2.ID_EMPLE, DATOS3;
FETCH DAT_EMPLEADO2 INTO DATOS2;
FETCH DAT_EMPLEADO3 INTO DATOS3;
END LOOP;
END $$
LANGUAGE 'plpgsql';