
CREATE OR REPLACE FUNCTION MOSTRAR_ENTRENADO(VARCHAR)
RETURNS TABLE (NOMBRE_CLIENTE VARCHAR(60),  NAME_EMPLEADO VARCHAR(60))
AS
$$
SELECT CLIENTE.NOMBRE_CLIENTE,EMPLEADO.NAME_EMPLEADO
FROM CONTRATO_MEMBRESIA 
INNER JOIN EMPLEADO ON CONTRATO_MEMBRESIA.ID_EMPLE= EMPLEADO.ID_EMPLE
INNER JOIN CLIENTE ON CONTRATO_MEMBRESIA.ID_CLIENT= CLIENTE.ID_CLIENT 
WHERE CLIENTE.NOMBRE_CLIENTE = $1;
$$
LANGUAGE'sql';


SELECT MOSTRAR_ENTRENADO('Soraya Serra')