--Consulta del resporte--


SELECT TIPO_MEMBRESIA.TIPO_MEMBRESIA AS MEMBRESIA,
COUNT(CONTRATO_MEMBRESIA.ID_TIPOMEMBRE) AS CANTIDAD
FROM CONTRATO_MEMBRESIA
INNER JOIN TIPO_MEMBRESIA ON CONTRATO_MEMBRESIA.ID_TIPOMEMBRE= TIPO_MEMBRESIA.ID_TIPOMEMBRE
GROUP BY TIPO_MEMBRESIA.TIPO_MEMBRESIA
ORDER BY COUNT(CONTRATO_MEMBRESIA.ID_TIPOMEMBRE) DESC;