
CREATE OR REPLACE FUNCTION RUTINA_CANTIDAD() RETURNS TRIGGER AS $RUTINA_CANTIDAD$ 
DECLARE
	CANTIDAD_N INT;
BEGIN
	SELECT COUNT(ID_RUTIN) INTO CANTIDAD_N FROM CLIENTE
	WHERE ID_RUTIN = NEW.ID_RUTIN;
	UPDATE RUTINA
	SET CANTIDAD_C  = CANTIDAD_N
	WHERE RUTINA.ID_RUTIN= NEW.ID_RUTIN;
	RETURN NEW;
END;
$RUTINA_CANTIDAD$
LANGUAGE plpgsql;


CREATE TRIGGER RUTINA_CANTIDAD
AFTER
INSERT OR UPDATE ON CLIENTE
FOR EACH ROW
EXECUTE PROCEDURE RUTINA_CANTIDAD();

INSERT INTO CLIENTE VALUES(12,5,'1457689091','Mariona EMosuera','0963452038','2020-10-21');


SELECT * FROM RUTINA